/*
 * SPDX-FileCopyrightText: Copyright 2025 LG Electronics Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

import * as _ from "lodash";

export const Country: { [key: string]: string } = {
    KR: "KR",
    AU: "AU",
    NZ: "NZ",
    JP: "JP",
    SG: "SG",
    US: "US",
    CA: "CA",
    GB: "GB",
    DE: "DE",
    IT: "IT",
    FR: "FR",
    HK: "HK",
    BD: "BD",
    CN: "CN",
    ID: "ID",
    IN: "IN",
    KH: "KH",
    LA: "LA",
    LK: "LK",
    MM: "MM",
    MY: "MY",
    NP: "NP",
    PH: "PH",
    TH: "TH",
    TW: "TW",
    VN: "VN",
    RU: "RU",
    AG: "AG",
    AR: "AR",
    AW: "AW",
    BB: "BB",
    BO: "BO",
    BR: "BR",
    BS: "BS",
    BZ: "BZ",
    CL: "CL",
    CO: "CO",
    CR: "CR",
    CU: "CU",
    DM: "DM",
    DO: "DO",
    EC: "EC",
    GD: "GD",
    GT: "GT",
    GY: "GY",
    HN: "HN",
    HT: "HT",
    JM: "JM",
    KN: "KN",
    LC: "LC",
    MX: "MX",
    NI: "NI",
    PA: "PA",
    PE: "PE",
    PR: "PR",
    PY: "PY",
    SR: "SR",
    SV: "SV",
    TT: "TT",
    UY: "UY",
    VC: "VC",
    VE: "VE",
    AE: "AE",
    AF: "AF",
    AL: "AL",
    AM: "AM",
    AO: "AO",
    AT: "AT",
    AZ: "AZ",
    BA: "BA",
    BE: "BE",
    BF: "BF",
    BG: "BG",
    BH: "BH",
    BJ: "BJ",
    BY: "BY",
    CD: "CD",
    CF: "CF",
    CG: "CG",
    CH: "CH",
    CI: "CI",
    CM: "CM",
    CV: "CV",
    CY: "CY",
    CZ: "CZ",
    DJ: "DJ",
    DK: "DK",
    DZ: "DZ",
    EE: "EE",
    EG: "EG",
    ES: "ES",
    ET: "ET",
    FI: "FI",
    GA: "GA",
    GE: "GE",
    GH: "GH",
    GM: "GM",
    GN: "GN",
    GQ: "GQ",
    GR: "GR",
    HR: "HR",
    HU: "HU",
    IE: "IE",
    IL: "IL",
    IQ: "IQ",
    IR: "IR",
    IS: "IS",
    JO: "JO",
    KE: "KE",
    KG: "KG",
    KW: "KW",
    KZ: "KZ",
    LB: "LB",
    LR: "LR",
    LT: "LT",
    LU: "LU",
    LV: "LV",
    LY: "LY",
    MA: "MA",
    MD: "MD",
    ME: "ME",
    MK: "MK",
    ML: "ML",
    MR: "MR",
    MT: "MT",
    MU: "MU",
    MW: "MW",
    NE: "NE",
    NG: "NG",
    NL: "NL",
    NO: "NO",
    OM: "OM",
    PK: "PK",
    PL: "PL",
    PS: "PS",
    PT: "PT",
    QA: "QA",
    RO: "RO",
    RS: "RS",
    RW: "RW",
    SA: "SA",
    SD: "SD",
    SE: "SE",
    SI: "SI",
    SK: "SK",
    SL: "SL",
    SN: "SN",
    SO: "SO",
    ST: "ST",
    SY: "SY",
    TD: "TD",
    TG: "TG",
    TN: "TN",
    TR: "TR",
    TZ: "TZ",
    UA: "UA",
    UG: "UG",
    UZ: "UZ",
    XK: "XK",
    YE: "YE",
    ZA: "ZA",
    ZM: "ZM",
    WW: "WW",
};

const DOMAIN_PREFIX: { [key: string]: string } = {
    KIC: "kic",
    AIC: "aic",
    EIC: "eic",
};

export const SUPPORTED_COUNTRIES: { [key: string]: string[] } = {
    [DOMAIN_PREFIX.KIC]: [
        Country.AU,
        Country.BD,
        Country.CN,
        Country.HK,
        Country.ID,
        Country.IN,
        Country.JP,
        Country.KH,
        Country.KR,
        Country.LA,
        Country.LK,
        Country.MM,
        Country.MY,
        Country.NP,
        Country.NZ,
        Country.PH,
        Country.SG,
        Country.TH,
        Country.TW,
        Country.VN,
    ],
    [DOMAIN_PREFIX.AIC]: [
        Country.AG,
        Country.AR,
        Country.AW,
        Country.BB,
        Country.BO,
        Country.BR,
        Country.BS,
        Country.BZ,
        Country.CA,
        Country.CL,
        Country.CO,
        Country.CR,
        Country.CU,
        Country.DM,
        Country.DO,
        Country.EC,
        Country.GD,
        Country.GT,
        Country.GY,
        Country.HN,
        Country.HT,
        Country.JM,
        Country.KN,
        Country.LC,
        Country.MX,
        Country.NI,
        Country.PA,
        Country.PE,
        Country.PR,
        Country.PY,
        Country.SR,
        Country.SV,
        Country.TT,
        Country.US,
        Country.UY,
        Country.VC,
        Country.VE,
    ],
    [DOMAIN_PREFIX.EIC]: [
        Country.AE,
        Country.AF,
        Country.AL,
        Country.AM,
        Country.AO,
        Country.AT,
        Country.AZ,
        Country.BA,
        Country.BE,
        Country.BF,
        Country.BG,
        Country.BH,
        Country.BJ,
        Country.BY,
        Country.CD,
        Country.CF,
        Country.CG,
        Country.CH,
        Country.CI,
        Country.CM,
        Country.CV,
        Country.CY,
        Country.CZ,
        Country.DE,
        Country.DJ,
        Country.DK,
        Country.DZ,
        Country.EE,
        Country.EG,
        Country.ES,
        Country.ET,
        Country.FI,
        Country.FR,
        Country.GA,
        Country.GB,
        Country.GE,
        Country.GH,
        Country.GM,
        Country.GN,
        Country.GQ,
        Country.GR,
        Country.HR,
        Country.HU,
        Country.IE,
        Country.IL,
        Country.IQ,
        Country.IR,
        Country.IS,
        Country.IT,
        Country.JO,
        Country.KE,
        Country.KG,
        Country.KW,
        Country.KZ,
        Country.LB,
        Country.LR,
        Country.LT,
        Country.LU,
        Country.LV,
        Country.LY,
        Country.MA,
        Country.MD,
        Country.ME,
        Country.MK,
        Country.ML,
        Country.MR,
        Country.MT,
        Country.MU,
        Country.MW,
        Country.NE,
        Country.NG,
        Country.NL,
        Country.NO,
        Country.OM,
        Country.PK,
        Country.PL,
        Country.PS,
        Country.PT,
        Country.QA,
        Country.RO,
        Country.RS,
        Country.RU,
        Country.RW,
        Country.SA,
        Country.SD,
        Country.SE,
        Country.SI,
        Country.SK,
        Country.SL,
        Country.SN,
        Country.SO,
        Country.ST,
        Country.SY,
        Country.TD,
        Country.TG,
        Country.TN,
        Country.TR,
        Country.TZ,
        Country.UA,
        Country.UG,
        Country.UZ,
        Country.XK,
        Country.YE,
        Country.ZA,
        Country.ZM,
    ],
};

export const getRegionFromCountry = (
    countryCode: string,
): string | undefined => {
    for (const domainPrefix of [
        DOMAIN_PREFIX.KIC,
        DOMAIN_PREFIX.AIC,
        DOMAIN_PREFIX.EIC,
    ]) {
        if (_.includes(SUPPORTED_COUNTRIES[domainPrefix], countryCode))
            return domainPrefix;
    }
    throw new Error("Not supported country_code.");
};
